title: DATA SCIENTIST 
url: "https://matejkovacc.github.io"
baseurl: "/datascientist"

markdown: kramdown


tracking_id: #

footer: yes
footer_url: "https://github.com/matejkovacc"
footer_text: "Page design by Matej KovaÄ"

sass:
    style: compressed
    sass_dir: _sass

nav:

   link: "/datascientist/"
 - name: "Resume"
   link: "Researcher.pdf"
 - name: "Contact"
   link: "contact"s
