title: DATA SCIENTIST 
url: "https://ankitsultana.com"
baseurl: "/datascientist"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/matejkovacc"
footer_text: "Page design by Matej KovaÄ"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/datascientist/"
 - name: "Resume"
   link: "Researcher.pdf"
 - name: "Contact"
   link: "contact"
